Hw01
catpasternak/epam-hw pull request #2
Opened 2021-06-26 10:48 UTC by catpasternak

2021-06-26 11:10 UTC, catpasternak commented
Коммит "Added homework01 directory" создавала тестово, в нем нет решений. Но так как удаление коммита - это новый коммит, решила пока не увеличивать энтропию:)

2021-06-27 10:59 UTC, i-n-samartsev requested changes

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task03.py
> +        lines = fi.readlines()
Не очень хороший вариант. файл может быть очень большим, и в памть не уместиться, поэтому если есть возможность, лучше перебирать строки в формате for line in fi

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task02.py
> +    if len(data) < 3:
теперь хотелось бы увидеть вариант не с 0,1,1, ... а с любого другого числа (например, с 5, 8, 13, 21 и тд).
тут в качестве одного из элементов языка которые тебе могут помочь  - это генератор-функции.
https://docs.python.org/3/tutorial/classes.html#generators
https://wiki.python.org/moin/Generators

и модуль itertools

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task02.py
> +    if len(data) < 3:
П.С. - генераторы и итертулз использовать можно, но не обязательно

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task04.py
> +    for i in a:
предложу тебе такой оптимизированный алгоритм: подсчитать сколько различных комбинаций элементов первых 2 списков дает какие суммы. (например -3 дадут 5 комбинаций), сколько различных комбинаций элементов  вторых 2  списков дадут какие суммы. Могут найтись  суммы с противоположным знаком, это будет значить что комбинации друг друга дополнят до 0

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task05.py
> +        return "List is empty."
ретурн сдесь делать некорректно, так как от функции ожидается все-таки число. верно тут будет поднять ошибку, например так - raise ValueError('List is Empty').
А вообще в питоне принято переносить ответственность за корректность параметров перекладывать на вызывающего, то есть проверки можно не делать совсем, и если будет какая-то нештатная ситуация, например попытаешься взять какой-то элемент из пустого списка, то совершенно логично вылетит ошибка, и это нормально.

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task05.py
> +    while k > 0:
while со счетчиком для перебора элементов в питоне не айс. используй range с параметром отрицательного шага.
for subarray_length in range(k, 1, -1):

2021-06-27 10:59 UTC, i-n-samartsev commented on homework01/task05.py
> +    while k > 0:
Желательно разделить мухи и котлеты. k - у тебя параметр - максимальная длина подмассива которые ты перебираешь. А дальше ты начинаешь этой переменной манипулировать (что уже не очень хорошо). Правильнее было бы завести другую переменную типа subarr_length - с говорящем именем и семантикой.

2021-06-27 10:59 UTC, i-n-samartsev commented on tests/homework01/test_task03.py
> +        os.path.join(os.path.dirname(__file__), "file01_task03.txt")
сделай короткой функцией, чтобы не повторять.
def _path_to(filename):
   ...

2021-06-27 17:12 UTC, catpasternak commented on homework01/task02.py
> +"""
Позже подумаю, как можно решить используя генератор и итератор.

2021-06-27 17:14 UTC, catpasternak commented on homework01/task04.py
> +    for i in a:
Переписала

2021-07-19 09:47 UTC, i-n-samartsev approved these changes

2021-07-29 12:31 UTC, merged