Hw04
catpasternak/epam-hw pull request #5
Opened 2021-07-06 20:54 UTC by catpasternak

2021-07-19 10:42 UTC, i-n-samartsev requested changes

2021-07-19 10:42 UTC, i-n-samartsev commented on homework04/task01.py
> +        raise ValueError
write a meaningful error message that can be derived from errors caught

2021-07-19 10:42 UTC, i-n-samartsev commented on homework04/task01.py
> +    else:
не нужен

2021-07-19 10:42 UTC, i-n-samartsev commented on homework04/task02.py
> +        else:
не нужен

2021-07-19 10:42 UTC, i-n-samartsev commented on tests/homework04/test_task01.py
> +def create_file_2(tmpdir):
ДОп Задание- сделать создание временного файла (с контентом)
при помощи параметризованного декоратора
@create_file(data)
def test_function(temp_filename )  # temp_filename is passed into this function. That file is prefilled with data

2021-07-19 10:42 UTC, i-n-samartsev commented on tests/homework04/test_task02.py
> +    with patch("homework04.task02.UrlResponse") as mock_request:
В качестве доп упражнения напиши свою реализацию контекстного менеджера patch.
тебе помогут в этом
__import__
sys.modules
getattr
setattr
hasattr

про менеджеры контекста слушай лекцию от 20.07, посмотри модуль contextlib. и прочитай про протокол менеджера контекста из этого дока https://docs.python.org/3/reference/datamodel.html#with-statement-context-managers

2021-07-30 17:20 UTC, catpasternak commented on tests/homework04/test_task02.py
> +    with patch("homework04.task02.UrlResponse") as mock_request:
Реализовала что-то похожее

2021-08-09 10:18 UTC, i-n-samartsev commented on homework04/task01.py
> +    except Exception:
Exception as err:
   можно использовать traceback.format_exc()
   или raise ValueError from err
   
  покопай модуль traceback

2021-08-09 10:27 UTC, i-n-samartsev commented on tests/homework04/test_task02.py
> +        modules = self.path_to_obj.split(".")
rsplit('.', 1)

2021-08-09 10:27 UTC, i-n-samartsev commented on tests/homework04/test_task02.py
> +        modules = self.path_to_obj.split(".")
strip()
rstrip()

2021-08-09 10:29 UTC, i-n-samartsev approved these changes

2021-08-17 10:45 UTC, merged