Homework 5
catpasternak/epam-hw pull request #6
Opened 2021-07-12 13:36 UTC by catpasternak

2021-07-19 10:49 UTC, i-n-samartsev requested changes
Добавить докстринги и попробовать погенерировать документацию из sphinx самостоятельно

2021-07-19 10:49 UTC, i-n-samartsev commented on homework05/task01.py
> +    """Homework task with deadline"""
когда ты подходишь к построению объектной модели своего приложения, очень важно все задокументировать правильно. Это "скелет" из логики и взаимосвязей которые будут в дальнейшем использоваться. Есть несколько форматов оформления докстрингов, самый распространенный - sphinx.
Вот небольшой гайд как писать докстринги на сфинксе
https://sphinx-rtd-tutorial.readthedocs.io/en/latest/docstrings.html

2021-08-09 10:30 UTC, i-n-samartsev commented
приложи к комментарию zip-файл с сгенерированной автодокументации к своим объектам

2021-08-17 15:22 UTC, catpasternak commented on homework05/task01.py
> +    """Homework task with deadline"""
> приложи к комментарию zip-файл с сгенерированной автодокументации к своим объектам

[task01.html.tar.gz](https://github.com/catpasternak/epam-hw/files/7001190/task01.html.tar.gz)

2022-03-23 21:26 UTC, merged